### ISSUE TITLE
Proposal Feeback

### ISSUE THREAD

**Issue by aplarson** [ShIxtan/Gamify#1]
My main question involves rewards: right now, they are added in phase 3, but it seems like you don't add the ability to purchase them until phase 4.  Maybe break up those phases differently: phase 3 add Dailies and To-Dos, phase 4 Rewards and Gold, Phase 5 XP and Health.

**Comment by ShIxtan** [comment]
CJ said much the same. I'll make these changes and move XP and health to bonus features.
